### ISSUE TITLE
Waterline ORM Support?

### ISSUE THREAD

**Issue by vgenev** [BesLogic/sails-mysql-atomic#20]
Hi guys, 

Congratulations on the great work! I have one question, though. 
Is it working with Waterline ORM and is there any examples if it is working?

**Comment by sam9291** [comment]
Hi @vgenev,

It actually requires Waterline ORM and Sails in order to work. This plugin is a sails hook that injects an adapter into waterline which slightly tweaks waterline to pass along the sql transaction to reuse inside Waterline ORM. You can look into the file "sails-mysql-atomic/api/adapters/adapter.js" for some of the wrapping logic and in the file "sails-mysql-atomic/test/transactions.spec.js" for some sample of how I use it.

**Comment by vgenev** [comment]
Thanks for the lead! I will try it little bit later, although I am using Waterline with Hapi, so no Sails... I forgot to mention that.

**Comment by sam9291** [comment]
Great, let me know if you manage to get it working with only waterline, I'm curious to know, never tested it :)
